<?php

/**
 * Distribuidor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Categoriareceta extends BaseCategoriareceta
{
	public function getRecetas()
	{
		$q=Doctrine_Query::create()->from('Categoriareceta')->orderBY('id');
			
		return $q->execute();	
	}	

}