<?php

/**
 * Receta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Receta extends BaseReceta
{
	
	function get_by_field($field,$value,$num=false)
	{
		$query = Doctrine_Query::create()
		->from('Receta')
		->where($field.' = ?', $value);
		
		if(!$num)
		return $query->execute()->getFirst();
		
		if($num && $num == 'ALL')
		return $query->execute();
	}
	
	

	function get_by_where($where,$num=false)
	{
		$query = Doctrine_Query::create()
		->from('Receta')
		->where($where);
		
		if(!$num)
		return $query->execute()->getFirst();
		
		if($num && $num == 'ALL')
		return $query->execute();
		
		if($num && $num != 'ALL')
		{
			$query->limit($num);
			return $query->execute();		
		}
	}



	
	function insert_data($post)
	{
		$insert = new Cliente();
		foreach($post as $k => $v)
		{			
			$insert->$k		= $v;
		}	
		$insert->save();
		return $insert->id;
	}
	
	
	
	
	function update_data($post,$id)
	{
		$update = Doctrine_Query::create()
		->update('Receta');
		foreach($post as $k=>$v)
		{

			$update->set($k, '?', $v);
		}
		$update->where('id = ?', $id);
		$update->execute();
	}
	
	

	function get_data_grid($where, $offset, $limit)
	{
		$query = Doctrine_Query::create()
		->from('Receta')
		->where(''.$where.'');
		$total=$query->count();
		$query->offset($offset);
		$query->limit($limit);
		return array('res'=>$query->execute(), 'total' => $total);
	}
	
	public function getRecetas()
	{
		$q=Doctrine_Query::create()->from('Receta')->orderBY('id');
			
		return $q->execute();	
	}
	
	public function geTituloes()
	{
		return strtolower($this->_get('titulo_es'));
	}
	
	public function geTituloen()
	{
		return strtolower($this->_get('titulo_en'));
	}	

}